source "https://rubygems.org"

# gem 'chef-pedant', :github => 'opscode/chef-pedant', :ref => "server-cli-option"
gem 'oc-chef-pedant', :github => 'chef/chef-server', branch: 'e9bf7fe4440afd34856401831b30636100be958b'